import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";

import Footer from "@/components/Footer";
import ScrollButton from "@/components/ScrollButton";
import AppBar from "@/components/AppBar";
import { Toaster } from "@/components/ui/toaster";
import LogoName from "@/components/LogoName";
import Carusel from "@/components/Carousel";
import { ThemeToggler } from "@/components/ThemeToggler";

// import { NavigationMenu } from "@/components/ui/navigation-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Сувениры из Волгограда",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <link rel="icon" href="public/favicon.svg" type="image/x-icon"></link>
      <link rel="icon" href="public/favicon.ico" type="image/x-icon"></link>
      <meta
        name="google-site-verification"
        content="EXibeSczwJN_4jXyyWcf7TdYabhR8HTPEsgj4CdzWkk"
      />
      <body className={inter.className}>
        <Providers>
          <div
            className="bg-blue-50 p-2 h-1/2"
            style={{
              backgroundImage: 'url("./bg-tel.png")',
            }}
          >
            <div className="absolute right-1 mr-3 mt-5 text-xs"></div>
            <LogoName />
            <AppBar />
            <div className="p-4 mt-5 shadow-lg rounded-md mb-4 relative">
              <h2 className="font-semibold text-lg text-blue-400 mb-3 text-center">
                Достопримечательности
              </h2>
              <div className="absolute inset-x-0 bottom-0 h-4 bg-gradient-to-t from-gray-300 to-transparent"></div>

              <Carusel />
            </div>
            <div className="mb-10"></div>
          </div>

          <div className="mt-5 flex gap-2 ml-24"></div>

          <main className="container py-6">{children}</main>
        </Providers>

        <Footer />
        <ScrollButton />
        <Toaster />
      </body>
    </html>
  );
}
